---
- name: Ensure Celery is installed
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{celery.requirements}}
    virtualenv={{common.virtualenv}}
  tags:
    - provision
    - deploy
