---
- name: Add rabbitmq apt respository
  apt_repository: >
    repo=deb http://www.rabbitmq.com/debian/ testing main
    state=present

- name: Add rabbitmq apt repository key
  apt_key: >
    url=wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    state=present

- name: Ensure rabbitmq is installed
  apt: >
    name={{item}}
    state=present
    update_cache=yes
  with_items:
    - rabbitmq-server