---
- name: Install app requirements
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{common.requirements}}
    virtualenv={{common.virtualenv}}
  tags:
    - provision

- name: Copy over local settings
  sudo: true
  sudo_user: "{{project.user}}"
  template: >
    src=local.py.j2
    dest={{django.root}}/legco-watch/local.py
    owner={{project.user}}
    group={{project.group}}
    mode=0664
  notify: Restart uWSGI
  when: not is_vagrant
  tags:
    - deploy
