---
- name: Install app requirements
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{common.requirements}}
    virtualenv={{common.virtualenv}}

#    - name: Create app user
#      user: >
#        name={{project.user}}
#        groups={{project.group}}
#        state=present
#

