---
- name: Install app requirements
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{common.requirements}}
    virtualenv={{common.virtualenv}}
  tags:
    - provision

- name: Copy over local settings
  sudo: true
  template: >
    src=local.py.j2
    dest={{django.root}}/legcowatch/local.py
    owner={{project.user}}
    group={{project.group}}
    mode=0664
  notify:
    - Restart uWSGI
  when: not is_vagrant
  tags:
    - deploy

# Collectstatic, syncdb, and migrate
- include: ../handlers/main.yml tags=deploy