---
- name: Install app requirements
  sudo: true
  sudo_user: "{{project.user}}"
  pip: >
    requirements={{common.requirements}}
    virtualenv={{common.virtualenv}}
  tags:
    - provision
    - deploy

# This will always be changed, since the repo has a different version of local.py
- name: Copy over local settings
  sudo: true
  template: >
    src=local.py.j2
    dest={{django.root}}/legcowatch/local.py
    owner={{project.user}}
    group={{project.group}}
    mode=0664
  notify:
    - Restart uWSGI
  when: not is_vagrant
  tags:
    - deploy

# Collectstatic, syncdb, and migrate
- include: ../handlers/main.yml tags=deploy

# Install bower dependencies
- name: Install bower dependencies
  sudo: true
  sudo_user: "{{project.user}}"
  shell: >
    source ~/.nvm/nvm.sh && nvm use && bower install
    chdir={{git.root}}
    executable=/bin/bash
  tags:
    - deploy

# This will create a user named 'legcowatch' with password 'changeme'
# Should only be run on provisions, otherwise
# it'll wipe out the first user every time it's run
- name: Create first superuser
  sudo: yes
  sudo_user: "{{project.user}}"
  django_manage: >
    app_path={{django.root}}
    virtualenv={{common.virtualenv}}
    command=loaddata
    fixtures=fixtures/superuser.json
  tags:
    - provision
