---
is_vagrant: true

database:
  user: legcowatchdb
  password: e8aVqxwaKVXMfBT
  name: legcowatch
  host: localhost
  port: 5432

project:
  user: vagrant
  user_home: /home/vagrant
  group: www-data
  root: /vagrant

common:
  virtualenv: /home/vagrant/envs/legcowatch
  requirements: /vagrant/requirements/base_reqs.txt
  logs_dir: "/var/log"

git:
  root: /vagrant

django:
  root: "{{git.root}}/app"
  static_dir: "{{git.root}}/app/.static"
  media_dir: "{{git.root}}/app/.media"
  debug: True

celery:
  requirements: /vagrant/requirements/celery_reqs.txt

scrapy:
  requirements: /vagrant/requirements/scrapy_reqs.txt

scrapyd:
  dir: /var/legco-watch/scrapyd
  address: http://localhost:6800/
  eggs_dir: /var/legco-watch/scrapyd/eggs
  logs_dir: /var/legco-watch/scrapyd/logs
  items_dir: /var/legco-watch/scrapyd/items
  debug: on
  files_dir: /var/legco-watch/scrapyd/files

uwsgi:
  logs_dir: "{{common.logs_dir}}/uwsgi"

nginx:
  logs_dir: "{{common.logs_dir}}/nginx"
