---
database:
  user: legcowatchdb
  password: e8aVqxwaKVXMfBT
  name: legcowatch
  host: localhost
  port: 5432

project:
  user: vagrant
  user_home: /home/vagrant
  group: www-data
  root: /vagrant
  virtualenv: /home/vagrant/envs/legcowatch
  requirements: /vagrant/requirements/requirements.txt

django:
  root: "{{project.root}}/app"

celery:
  requirements: /vagrant/celery_reqs.txt
