---
is_vagrant: false

database:
  user: legcowatchdb
  password: e8aVqxwaKVXMfBT
  name: legcowatch
  host: localhost
  port: 5432

project:
  user: legco-watch
  user_home: /home/legco-watch
  group: www-data
  root: /var/www
  virtualenv: /home/legco-watch/envs/legcowatch
  requirements: /var/www/requirements/base_reqs.txt

django:
  root: "{{project.root}}/app"

celery:
  requirements: "{{project.root}}/requirements/celery_reqs.txt"

scrapy:
  requirements: "{{project.root}}/requirements/scrapy_reqs.txt"

scrapyd:
  address: http://192.168.221.4:6800/
  eggs_dir: /var/lib/scrapyd/eggs
  logs_dir: /var/lib/scrapyd/logs
  items_dir: /var/lib/scrapyd/items
  debug: on
  files_dir: /var/scraper/files
